/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: CoverUrl
 * Author: Victor
 * Date: 2023/06/16 16:14
 * Description: 
 * -----------------------------------------------------------------
 */

export class CoverUrl {
  raw: string
  full: string
  regular: string
  small: string
  thumb: string
  small_s3: string
}