/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: Link
 * Author: Victor
 * Date: 2023/07/07 17:14
 * Description: 
 * -----------------------------------------------------------------
 */
 export class Link{
   self: string;
   html: string;
   download: string;
   download_location: string;
 }
 