/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: ProfileImageInfo
 * Author: Victor
 * Date: 2023/07/07 17:20
 * Description: 
 * -----------------------------------------------------------------
 */
 export class ProfileImageInfo {
   small: string;
   medium: string;
   large: string;
 }
 