/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: SearchCategoryInfo
 * Author: Victor
 * Date: 2023/07/10 15:54
 * Description: 
 * -----------------------------------------------------------------
 */
export class SearchCategoryInfo{
  category: string
  image: Resource
}
 
 