/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: UserLinkInfo
 * Author: Victor
 * Date: 2023/07/07 17:17
 * Description: 
 * -----------------------------------------------------------------
 */
 export class UserLinkInfo {
   self: string;
   html: string;
   photos: string;
   likes: string;
   portfolio: string;
   following: string;
   followers: String
 }
 