/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: MyCollectionsTabContent
 * Author: Victor
 * Date: 2023/07/11 17:54
 * Description: 
 * -----------------------------------------------------------------
 */
@Component
@Preview
export struct MyCollectionsTabContent {
  build() {
    Column() {
      Text('Collections').fontColor(Color.Blue).fontSize(36).textAlign(TextAlign.Start)
    }
  }
}
 