/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: HomeApi
 * Author: Victor
 * Date: 2023/06/16 14:31
 * Description: 
 * -----------------------------------------------------------------
 */

export class HomeApi {
  static readonly TOPICS = 'https://api.unsplash.com/topics?client_id=xc-uXz4GlgUeFsZPgWZICrGo_dfeQs4QvJmrzDMIkfo&page=1&per_page=20'

  static readonly TAG = 'http://baobab.kaiyanapp.com/api/v7/tag/tabList'//
}