/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: Constants
 * Author: Victor
 * Date: 2023/06/16 12:14
 * Description: 
 * -----------------------------------------------------------------
 */

export default class Constants {
  static readonly MATCH_PARENT: string = '100%';
}