/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: Constants
 * Author: Victor
 * Date: 2023/06/16 12:14
 * Description: 
 * -----------------------------------------------------------------
 */

export default class Constants {
  static readonly DATA = 'data';
  static readonly TITLE = 'title';
  static readonly POSITION = 'position';
  static readonly URL = 'url';
  static readonly SHARE_ID = 'shareId';
  static readonly TOPIC_ID = 'topicId';
  static readonly USER_ID = 'userId';

  static readonly MATCH_PARENT: string = '100%';
  static readonly SWIPER_DATA_TAG: string = 'SWIPER_DATA_TAG';
  static readonly TRANSITION_ANIMATION_DURATION: number = 500;
  static readonly SHARE_ITEM_ANIMATION_DELAY = 100;

  static readonly TRANSPARENT_COLOR: string = '#00ffffff';
}