/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: RouterPath
 * Author: Victor
 * Date: 2023/6/16 11:55
 * Description: 
 * -----------------------------------------------------------------
 */
export default class RouterPath {
  static readonly INDEX_PAGE = 'pages/Index';
  static readonly PHOTO_DETAIL_PAGE = 'pages/PhotoDetailPage';
}