/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: HotTabModel
 * Author: Victor
 * Date: 2023/2/27 14:53
 * Description: 
 * -----------------------------------------------------------------
 */

export const searchHints = [
  'Search photos', 'Search collections', 'Search users'
]

export const searchCategorys = [
  {category: 'Natrue',image:$r('app.media.img_nature')},
  {category: 'Black and White',image:$r('app.media.img_black_and_white')},
  {category: 'Space',image:$r('app.media.img_space')},
  {category: 'Animals',image:$r('app.media.img_animals')},
  {category: 'Flowers',image:$r('app.media.img_flowers')},
  {category: 'Underwater',image:$r('app.media.img_under_water')},
  {category: 'Architecture',image:$r('app.media.img_architecture')},
  {category: 'Textures',image:$r('app.media.img_textures')},
  {category: 'Abstract',image:$r('app.media.img_abstract')},
  {category: 'Minimal',image:$r('app.media.img_minimal')},
  {category: 'Sky',image:$r('app.media.img_sky')},
  {category: 'Travel',image:$r('app.media.img_travel')},
  {category: 'Drones',image:$r('app.media.img_drones')},
  {category: 'Gradients',image:$r('app.media.img_gradients')},
]